### PR TITLE
feat(rule): support expires block comment

### PR DESCRIPTION
**Pull request by cogell**
- add valid and invalid block comment exipres tests

I was wanting this feature so I could write blocks like:
```
/**
 * EXPIRES: 2017-01-01
 *
 * TODO: after this date do that thing you need to remember to do
 */
```

### CODE REVIEW

**Comment by cogell** [comment]
caught a bug, updating...

**Comment by digencer** [comment]
Hi @cogell, thank you for your contribution 😊

**Comment by cogell** [comment]
of course, thanks for the plugin!

**Comment by cogell** [comment]
if you do a release I'll be able to switch our project back over to your fork.

**Comment by digencer** [comment]
I just published the version 1.1.0

**Pull request merged**
